apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sshd-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd-1
  template:
    metadata:
      labels:
        app: sshd-1
    spec:
      containers:
      - name: sshd-1
        image: sshd:1.0
        imagePullPolicy: IfNotPresent
#        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]


---
apiVersion: v1
kind: Service
metadata:
  name: sshd-nodeport
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30124
  selector:
    app: sshd-1


---
apiVersion: v1
kind: Service
metadata:
  name: sshd-web-nodeport-1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: sshd-1

